/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(compressing_pluto_source.h) */
/* BINDTOOL_HEADER_FILE_HASH(112fc5f109b1f13eecb0790a0747a60b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <sparsdr/compressing_pluto_source.h>
// pydoc.h is automatically generated in the build directory
#include <compressing_pluto_source_pydoc.h>

void bind_compressing_pluto_source(py::module& m)
{

    using compressing_pluto_source = gr::sparsdr::compressing_pluto_source;


    py::class_<compressing_pluto_source,
               gr::block,
               gr::basic_block,
               std::shared_ptr<compressing_pluto_source>>(
        m, "compressing_pluto_source", D(compressing_pluto_source))

        .def(py::init(&compressing_pluto_source::make),
             py::arg("uri"),
             py::arg("buffer_size") = 1024 * 1024,
             D(compressing_pluto_source, make))


        ;
}
